#!/bin/bash

# Check if Waybar is running
if pgrep -x "waybar" > /dev/null
then
    # If running, kill Waybar to hide it
    pkill waybar
else
    # If not running, start Waybar to show it
    hyprctl dispatch exec waybar &
fi
