# Default colors
[colors.primary]
  background = '#1a1b26'
  foreground = '#a9b1d6'

# Normal colors
[colors.normal]
  black   = '#414868'
  red     = '#f7768e'
  green   = '#73daca'
  yellow  = '#e0af68'
  blue    = '#7aa2f7'
  magenta = '#bb9af7'
  cyan    = '#7dcfff'
  white   = '#c0caf5'

# Bright colors
[colors.bright]
  black   = '#444b6a'
  red     = '#ff7a93'
  green   = '#b9f27c'
  yellow  = '#ff9e64'
  blue    = '#7da6ff'
  magenta = '#bb9af7'
  cyan    = '#0db9d7'
  white   = '#acb0d0'